theme = "Catppuccin Macchiato"
default_source = "SukebeiNyaa"
download_client = "DefaultApp"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client.command]
cmd = 'curl "{torrent}" > ~/{file}'
shell_cmd = "sh -c"

[client.qBittorrent]
base_url = "http://localhost:8080"

[client.default_app]
use_magnet = false

[client.download]
save_dir = "/home/comp/Downloads"
overwrite = true
create_root_folder = true

[source.nyaa]
base_url = "https://nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false

[source.sukebei]
base_url = "https://sukebei.nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false

[source.torrentgalaxy]
base_url = "https://torrentgalaxy.to/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
